/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openstreetmap.osmosis.kakasi.common.jni;

public class kakasi {
  public static int kakasi_getopt_argv(String[] argc) {
    return kakasiJNI.kakasi_getopt_argv(argc);
  }

  public static String kakasi_do(byte[] str) {
    return kakasiJNI.kakasi_do(str);
  }

  public static int kakasi_close_kanwadict() {
    return kakasiJNI.kakasi_close_kanwadict();
  }

  public static int kakasi_free(String p) {
    return kakasiJNI.kakasi_free(p);
  }

}
