/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openstreetmap.osmosis.kakasi.common;

public class kakasiJNI {
  public final static native int kakasi_getopt_argv(int jarg1, String[] jarg2);

  public final static native String kakasi_do(String jarg1);

  public final static native int kakasi_close_kanwadict();

  public final static native int kakasi_free(String jarg1);
}
